@extends('layouts.writer')
@section('title', __('Privacy · ').config('app.name'))
@section('content')
<main class="legal-page"><p class="eyebrow">{{ config('app.name') }}</p><h1>{{ __('Privacy policy') }}</h1><p>{{ __('Last updated: September 11, 2026') }}</p>
<h2>{{ __('Information we collect') }}</h2><p>{{ __('We store the information you provide to operate your account, including your name, email address, securely hashed password, manuscripts, codex entries, chat messages, preferences, revisions, and AI usage records. Contact forms store your name, email, subject, and message in our database.') }}</p>
<h2>{{ __('How we use it') }}</h2><p>{{ __('We use this information to provide the writing workspace, save and recover your work, authenticate your account, respond to contact requests, and monitor AI usage. We do not sell your manuscripts or contact information.') }}</p>
<h2>{{ __('AI providers and optional services') }}</h2><p>{{ __('When you request AI assistance, the configured OpenRouter service and selected model provider receive the prompt and relevant context. Regular requests can include the full manuscript and codex; selection requests include the selected text, nearby context, and codex. Your chosen chat history is included. Review the provider’s policies before submitting sensitive information.') }}</p><p>{{ __('If enabled, Google sign-in shares your verified email, name, and Google account identifier with us. If email delivery is configured, Mailgun processes recipient addresses and email content for account-related messages. Contact submissions are stored locally in our database and do not trigger email.') }}</p>
<h2>{{ __('Cookies, local storage, and logs') }}</h2><p>{{ __('We use cookies for authentication and request security, and browser storage for appearance preferences and draft recovery. AI call logs may contain full prompts and responses, including your writing and chat context. Personal API keys are encrypted in storage and are not included in request logs.') }}</p>
<h2>{{ __('Retention and your choices') }}</h2><p>{{ __('We retain account data and writing while needed to provide the service. Deleted books may remain recoverable until permanently removed. Operational logs and backups may persist separately. You can export your manuscript, manage your account, and contact us to request access, correction, or deletion of personal information. Requests are assessed under applicable requirements.') }}</p>
<h2>{{ __('Security and updates') }}</h2><p>{{ __('We use access controls and other safeguards, but no storage or transmission method is completely secure. This policy may change as the service evolves. Significant changes will be reflected on this page.') }}</p><h2>{{ __('Contact') }}</h2><p>{{ __('Use the contact form below for privacy questions or requests.') }}</p></main>
@include('partials.public-footer')
@endsection