@extends('layouts.writer')
@section('title', __('Terms · ').config('app.name'))
@section('content')
<main class="legal-page"><p class="eyebrow">{{ config('app.name') }}</p><h1>{{ __('Terms of use') }}</h1><p>{{ __('Last updated: September 11, 2026') }}</p>
<h2>{{ __('Using the service') }}</h2><p>{{ __('By using :app, you agree to these terms. Keep your login details secure, provide accurate account information, and use the service lawfully. Do not attempt to access another person’s account, interfere with the service, or upload content you do not have permission to use.', ['app' => config('app.name')]) }}</p>
<h2>{{ __('Your writing') }}</h2><p>{{ __('You retain your rights to the writing and other content you provide. You authorize us to store, process, and transmit it as needed to provide the features you use, including sending context to AI providers when you request assistance. You are responsible for permissions relating to third-party content.') }}</p>
<h2>{{ __('AI assistance') }}</h2><p>{{ __('AI output can be inaccurate, inconsistent, or similar to other material. Review all suggestions before relying on or publishing them. The app requires approval before applying AI edits; you remain responsible for the final manuscript and its use. We do not guarantee originality, factual accuracy, or a particular creative outcome.') }}</p>
<h2>{{ __('Usage and external services') }}</h2><p>{{ __('AI requests may incur provider charges. Demo allowances are limited, and personal API-key charges are governed by your provider agreement. Displayed estimates may differ from final provider usage. Model availability, pricing, and external services may change. Budget and context limits may prevent a request.') }}</p>
<h2>{{ __('Availability and backups') }}</h2><p>{{ __('Features may change or be temporarily unavailable. Keep independent exports of important work. The service is provided as available without guarantees of uninterrupted operation or fitness for a particular purpose, to the extent permitted by law.') }}</p>
<h2>{{ __('Account restrictions and liability') }}</h2><p>{{ __('We may restrict access for abuse, security risks, or violations of these terms. To the extent permitted by law, we are not responsible for indirect losses arising from use of the service. Nothing here excludes rights or liabilities that cannot lawfully be excluded.') }}</p>
<h2>{{ __('Changes and contact') }}</h2><p>{{ __('We may update these terms as the service changes. Continued use after updates means acceptance of the updated terms, subject to applicable law. Contact us below with questions.') }}</p></main>
@include('partials.public-footer')
@endsection