// Export only strings used by JavaScript; Laravel remains the source of translations.
const fs = require('fs');
const acorn = require('acorn');
const catalog = JSON.parse(fs.readFileSync('lang/en.json', 'utf8'));
const keys = new Set(['Light','Dark','Paper','light','dark','paper','People','Places','Items','Organizations','Events','Lore','Before AI changes','Before codex deletion','Before revision restore','Book settings','Codex edit','Manuscript save','New book','pending','approved','rejected']);
function walk(node) {
    if (!node || typeof node !== 'object') return;
    if (node.type === 'Literal' && typeof node.value === 'string' && Object.hasOwn(catalog, node.value)) keys.add(node.value);
    for (const value of Object.values(node)) {
        if (Array.isArray(value)) value.forEach(walk);
        else if (value && typeof value === 'object') walk(value);
    }
}
for (const file of fs.readdirSync('resources/js').filter(file => file.endsWith('.js'))) {
    walk(acorn.parse(fs.readFileSync('resources/js/' + file, 'utf8'), {ecmaVersion: 'latest', sourceType: 'module'}));
}
const php = [...keys].sort().map(key => "    '" + key.replaceAll('\\','\\\\').replaceAll("'", "\\'") + "',").join('\n');
fs.writeFileSync('config/frontend_translations.php', '<?php\n// Generated by npm run build/dev. Edit lang/*.json and JavaScript t() calls.\nreturn [\n' + php + '\n];\n');
console.log('Exported ' + keys.size + ' frontend translation keys.');
